name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v4
        run: fluentci run bun_pipeline run test build

      - name: Publish to Cloudflare Pages
        run: fluentci run cloudflare_pipeline pages-deploy
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          PROJECT_NAME: fluentci
          DIRECTORY: dist
