name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Nix
        run: |
          sudo apt-get update
          sudo apt-get install -y nix
          nix --version

      - name: Clone repository and setup environment
        run: |
          git clone https://github.com/fluentci-io/fluentci-engine.git
          cd fluentci-engine
          nix develop

      - name: Start FluentCI Engine
        run: |
          cd fluentci-engine
          cargo build -p fluentci-engine

      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5
        with:
          wasm: true  # Enable WebAssembly plugins if needed
          pipeline: rust  # Example pipeline setup if applicable

      - name: Deploy to Cloudflare Workers
        run: |
          cd fluentci-engine
          fluentci run --wasm cloudflare deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}



