name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workers: [worker1, worker2] # Adjust based on your workers setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Fluent CI
        uses: fluentci-io/setup-fluentci@v5

      - name: Deploy to Cloudflare Workers
        run: fluentci run --wasm cloudflare deploy
        working-directory: ./workers/${{ matrix.workers }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

